id = "keepcalm"
name = "KeepCalm"
schema_version = 1
version = "1.0.1"
authors = ["Sergio Garc√≠a Mondaray <sgmonda@gmail.com>"]
description = "A calm and focused theme for software development in Zed"
repository = "https://github.com/sgmonda/keepcalm-zed"
